In [1]:
import pandas as pd
import numpy as np
from collections import Counter
import os

In [10]:
file_names = ["https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_11_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_13_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_14_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_15_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_17_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_19_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_20_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_21_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_22_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_23_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_24_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_25_21.csv",
             "https://raw.githubusercontent.com/eggtgg/CapDoVungDich/main/data/ban_mau_12_26_21.csv"]


In [11]:
dfs = []
for name in file_names:
    dfs.append(pd.read_csv(name))

In [12]:
from functools import reduce

In [13]:
df_final = reduce(lambda left,right: pd.merge(left,right,on=["huyen", "xa", "thon"]), dfs)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'cap_x'} in the result is deprecated and will raise a MergeError in a future version.
  """Entry point for launching an IPython kernel.


In [14]:
df_final

huyen             xa                  thon  cap_x  cap_y  \
0        Thành phố Huế   Xã Hương Thọ         Thôn Định Môn      1      1   
1        Thành phố Huế   Xã Hương Thọ          Thôn Hòa An      1      1   
2        Thành phố Huế   Xã Hương Thọ         Thôn Kim Ngọc      1      1   
3        Thành phố Huế   Xã Hương Thọ      Thôn La Khê Trẹm      1      1   
4        Thành phố Huế   Xã Hương Thọ        Thôn Liên Bằng      1      1   
...                ...            ...                   ...    ...    ...   
1102  Thị xã Hương Trà  Xã Hương Toàn        Thôn Giáp Đông      2      2   
1103  Thị xã Hương Trà  Xã Hương Toàn         Thôn Giáp Tây      2      2   
1104  Thị xã Hương Trà  Xã Hương Toàn      Thôn Giáp Thượng      2      2   
1105  Thị xã Hương Trà  Xã Hương Toàn  Thôn Triều Sơn Trung      2      2   
1106  Thị xã Hương Trà  Xã Hương Toàn      Thôn Liễu Cốc Hạ      3      3   

      cap_x  cap_y  cap_x  cap_y  cap_x  cap_y  cap_x  cap_y  cap_x  cap_y  \
0         1      1      1      1      1      1      1      1      1      1   
1         1      1      1      1      1      1      1      1      1      1   
2         1      1      1      1      1      1      1      1      1      1   
3         1      1      1      1      1      1      1      1      1      1   
4         1      1      1      1      1      1      1      1      1      1   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1102      2      2      2      2      2      2      2      2      2      2   
1103      2      2      2      2      1      1      1      1      1      1   
1104      1      1      1      1      2      2      2      2      3      3   
1105      1      1      1      1      1      1      1      1      1      1   
1106      2      2      2      2      2      2      3      3      2      2   

      cap  
0       1  
1       1  
2       1  
3       1  
4       1  
...   ...  
1102    1  
1103    1  
1104    3  
1105    1  
1106    2  

[1107 rows x 16 columns]

In [15]:
a = len(df_final.columns[3:])

In [16]:
list(range(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [17]:
columns = ['huyen', 'xa', 'thon'] + list(range(a))

In [18]:
df_final.columns = columns

In [19]:
df_final

huyen             xa                  thon  0  1  2  3  4  5  \
0        Thành phố Huế   Xã Hương Thọ         Thôn Định Môn  1  1  1  1  1  1   
1        Thành phố Huế   Xã Hương Thọ          Thôn Hòa An  1  1  1  1  1  1   
2        Thành phố Huế   Xã Hương Thọ         Thôn Kim Ngọc  1  1  1  1  1  1   
3        Thành phố Huế   Xã Hương Thọ      Thôn La Khê Trẹm  1  1  1  1  1  1   
4        Thành phố Huế   Xã Hương Thọ        Thôn Liên Bằng  1  1  1  1  1  1   
...                ...            ...                   ... .. .. .. .. .. ..   
1102  Thị xã Hương Trà  Xã Hương Toàn        Thôn Giáp Đông  2  2  2  2  2  2   
1103  Thị xã Hương Trà  Xã Hương Toàn         Thôn Giáp Tây  2  2  2  2  2  2   
1104  Thị xã Hương Trà  Xã Hương Toàn      Thôn Giáp Thượng  2  2  1  1  1  1   
1105  Thị xã Hương Trà  Xã Hương Toàn  Thôn Triều Sơn Trung  2  2  1  1  1  1   
1106  Thị xã Hương Trà  Xã Hương Toàn      Thôn Liễu Cốc Hạ  3  3  2  2  2  2   

      6  7  8  9  10  11  12  
0     1  1  1  1   1   1   1  
1     1  1  1  1   1   1   1  
2     1  1  1  1   1   1   1  
3     1  1  1  1   1   1   1  
4     1  1  1  1   1   1   1  
...  .. .. .. ..  ..  ..  ..  
1102  2  2  2  2   2   2   1  
1103  1  1  1  1   1   1   1  
1104  2  2  2  2   3   3   3  
1105  1  1  1  1   1   1   1  
1106  2  2  3  3   2   2   2  

[1107 rows x 16 columns]

In [20]:
data = df_final[df_final.columns[3:]].to_numpy()
data

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [2, 2, 1, ..., 3, 3, 3],
       [2, 2, 1, ..., 1, 1, 1],
       [3, 3, 2, ..., 2, 2, 2]])

In [21]:
for i in data:
    print(i,'hello')

[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[2 2 2 2 2 2 2 2 2 2 2 2 1] hello
[3 3 3 3 3 3 3 3 3 1 1 2 2] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 2 1 1 1 1 1 2 2] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 1 1 1 1 1 1 2 2 2 2] hello
[1 1 1 2 2 3 3 3 3 3 3 2 2] hello
[1 1 1 1 1 1 2 2 2 2 2 2 2] hello
[2 2 2 1 1 1 1 1 1 1 1 2 3] hello
[3 3 3 2 2 2 3 3 3 3 3 3 3] hello
[1 1 2 2 2 2 2 2 2 2 2 2 2] hello
[1 1 1 1 1 1 1 1 1 1 1 2 2] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[1 1 1 2 2 3 3 3 3 3 3 3 3] hello
[1 1 1 1 1 1 1 1 1 1 1 1 1] hello
[2 2 2 2 2 2 1 1 1 1 1 1 1] hello
[2 2 2 2 2 2 2 2 2 2 2 2 2] hello
[3 3 3 3 3 3 2 2 2 1 1 1 1] hello
[1 1 1 1 1 1 2 2 1 1 1 1 1] hello
[1 1 2 2 2 2 3 3 3 3 3 2 2] hello
[1 1 2 2 2 2 2 2 2 2 2 2 2] hello
[1 1 1 2 2 2 3 3 3 3 3 3 3] hello
[2 2 2 2 2 2 2

In [22]:
so_ngay_truoc = 6
d = len(file_names) - so_ngay_truoc

In [23]:
x = []
y = []
for i in data:
    for j in range(d):
        x.append(i[j:j+so_ngay_truoc])
        y.append(i[j+so_ngay_truoc])

In [24]:
y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,


In [25]:
x_train = []
for x_tr in x:
    x_dem = [0, 0, 0, 0]
    for (i,x_tri) in enumerate(x_tr):
        x_dem[x_tri-1]+=(1+i)
    x_train.append(x_dem) 

In [26]:
x_train

[[21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [6, 0, 15, 0],
 [11, 0, 10, 0],
 [9, 6, 6, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0,

In [27]:
for (i,x_tri) in enumerate(x_train):
    print(x_tri,' ',y[i])

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[15, 6, 0, 0]   2
[10, 11, 0, 0]   2
[6, 15, 0, 0]   2
[3, 18, 0, 0]   2
[1, 20, 0, 0]   3
[0, 15, 6, 0]   3
[0, 10, 11, 0]   3
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   3
[15, 0, 6, 0]   3
[10, 0, 11, 0]   3
[6, 0, 15, 0]   3
[3, 0, 18, 0]   3
[1, 0, 20, 0]   3
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   3
[15, 0, 6, 0]   3
[10, 0, 11, 0]   3
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   1
[21, 0, 0, 0]   2
[15, 6, 0, 0]   2
[10, 11, 0, 0]   2
[1, 0, 20, 0]   3
[0, 0, 21, 0]   3
[0, 0, 21, 0]   3
[0, 0, 21, 0]   3
[0, 0, 21, 0]   3
[0, 0, 21, 0]   3
[0, 0, 21, 0]   1
[1, 0, 20, 0]   3
[0

In [28]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np 

In [29]:
clf = MultinomialNB()

In [30]:
clf.fit(x_train, y)

MultinomialNB()

In [31]:
def view_data(n):
    print(x[n])
    print(x_train[n])
    print(y[n])

In [32]:
x_train

[[21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 21, 0, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [0, 0, 21, 0],
 [6, 0, 15, 0],
 [11, 0, 10, 0],
 [9, 6, 6, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0, 0, 0],
 [21, 0,

In [33]:
view_data(356)

[1 1 1 1 1 1]
[21, 0, 0, 0]
1


In [34]:
d5 = np.array([x_train[14]])

In [35]:
d5 = np.array([[0,0,0,1]])

In [36]:
print('Predicting class of d5:', str(clf.predict(d5)))
print('Predicting class of d5:', str(clf.predict_proba(d5)[0]))

Predicting class of d5: [4]
Predicting class of d5: [6.41065534e-04 2.11538808e-02 1.65389936e-01 8.12815117e-01]


In [37]:
clf.score(x_train,y)

0.8403664989030842